print("Reference for croping")
reference <- raster(file.choose())
print("Raster to be cropped")
tobecroped <- raster(file.choose())
#output <- readline(prompt="Enter a name for output file: ")
croped <- crop(tobecroped, reference)
print("where to save")
writeRaster(croped, filename = file.choose())
